# remote_theme: just-the-docs/just-the-docs
theme: just-the-docs

incremental: true

course: "CMPSC 156"
title: "CS156 f24"
quarter: "Fall 2024"
QXX: f24
qxx: f24
baseurl: "/f24"
slack_help_lecture_discussion: https://ucsb-cs156-f24.slack.com/archives/C07P9T925KL

ta_list_full: TBD
la_list_full: TBD
discussion_section_day: Wednesday
discussion_section_times: 4pm, 5pm

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

# Aux links for the upper right navigation
aux_links:
  "CS156 main website":
    - "https://ucsb-cs156.github.io/"
  "Canvas":
    - "https://www.canvas.ucsb.edu"

# TODO: replace canvas link above with specific one
# such as https://www.canvas.ucsb.edu/courses/12345

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/ucsb-cs156/f24" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

help_macos_link: https://ucsb-cs156-f24.slack.com/
help_windows_link: https://ucsb-cs156-f24.slack.com/

# Collections for website data
collections:
  modules:
  staffers:
    permalink: "/:path/"
    output: true
  lectures:
    permalink: "/lectures/:path/"
    output: true
  hwk:
    permalink: "/hwk/:path/"
    output: true
# Default layouts for each collection type
defaults:
  - scope:
      type: lectures
    values:
      layout: default
  - scope:
      type: hwk
    values:
      layout: default
  - scope:
      path: ""
      type: staffers
    values:
      layout: staffer
      subpath: "/assets/images/"

teams: 
  - team: f24-01
    dokku: 01
    slack: https://ucsb-cs156-f24.slack.com/archives/C07PYJKCWEL
  - team: f24-02
    dokku: 02
    slack: https://ucsb-cs156-f24.slack.com/archives/C07P9QKLCSW
  - team: f24-03
    dokku: 03
    slack: https://ucsb-cs156-f24.slack.com/archives/C07P9QLJ4JW
  - team: f24-04
    dokku: 04
    slack: https://ucsb-cs156-f24.slack.com/archives/C07NV8JN50F
  - team: f24-05
    dokku: 05
    slack: https://ucsb-cs156-f24.slack.com/archives/C07NV8KDQQ7
  - team: f24-06
    dokku: 06
    slack: https://ucsb-cs156-f24.slack.com/archives/C07P36DJ35L
  - team: f24-07
    dokku: 07
    slack: https://ucsb-cs156-f24.slack.com/archives/C07P36EHA06
  - team: f24-08
    dokku: 08
    slack: https://ucsb-cs156-f24.slack.com/archives/C07PNFDK20Z
  - team: f24-09
    dokku: 09
    slack: https://ucsb-cs156-f24.slack.com/archives/C07PNFEB2EM
  - team: f24-10
    dokku: 10
    slack: https://ucsb-cs156-f24.slack.com/archives/C07P9QS5090
  - team: f24-11
    dokku: 11
    slack: https://ucsb-cs156-f24.slack.com/archives/C07P9N217AP
  - team: f24-12
    dokku: 12
    slack: https://ucsb-cs156-f24.slack.com/archives/C07PCA3GTBN
  - team: f24-13
    dokku: 13
    slack: https://ucsb-cs156-f24.slack.com/archives/C07P9QU0BKL
  - team: f24-14
    dokku: 14
    slack: https://ucsb-cs156-f24.slack.com/archives/C07PCA4MFMJ
  - team: f24-15
    dokku: 15
    slack: https://ucsb-cs156-f24.slack.com/archives/C07P36L8SHL
  - team: f24-16
    dokku: 16
    slack: https://ucsb-cs156-f24.slack.com/archives/C07NV8T9415
